name: inkloodle

services:
  caddy:
    image: caddy:2.7
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy_data:/data
      - /data/caddy_config:/config

  webserver:
    image: 905418360736.dkr.ecr.eu-central-1.amazonaws.com/inkloodle:IMAGE_TAG
    volumes:
      - /data/moodle:/var/www/moodledata
    depends_on:
      - db
    environment:
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBHOST: db
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBPASS: $DB_PASSWORD
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_WEB_HOST: https://moodle.cesko.dev
  db:
    image: mariadb:11.3
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --innodb_file_per_table=On
      - --wait-timeout=28800
      - --skip-log-bin
    environment:
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
      MARIADB_PASSWORD: $DB_PASSWORD
      MARIADB_ROOT_PASSWORD: $ROOT_DB_PASSWORD
    volumes:
      - /data/db:/var/lib/mysql
