<?php
/*
@edmoRef: @theme_edmo/layout
 */

defined('MOODLE_INTERNAL') || die();

$templatecontext = [
    'sitename'                  => format_string($SITE->shortname, true, ['context' => context_course::instance(SITEID), "escape" => false]),
    'output'                    => $OUTPUT,
    'pageheading'               => $pageheading,
    'leftblocks'                => $leftblocks,
    'user_profile_picture'      => new moodle_url('/user/pix.php/'.$USER->id.'/f1.jpg'),
    'profile_icon_username'     => $edmoProfileIconUsername,
    'login_url'                 => $login_url,
    'isloggedin'                => $isloggedin,
    'sidepreblocks'             => $blockshtml,
    'hasblocks'                 => $hasblocks,
    'bodyattributes'            => $bodyattributes,
    'primarymoremenu'           => $primarymenu['moremenu'],
    'secondarymoremenu'         => $secondarynavigation ?: false,
    'mobileprimarynav'          => $primarymenu['mobileprimarynav'],
    'usermenu'                  => $primarymenu['user'],
    'langmenu'                  => $primarymenu['lang'],
    'headercontent'             => $headercontent,
    'overflow'                  => $overflow,
    'addblockbutton'            => $addblockbutton,
    'blocks_fullwidth_top'      => $blocks_fullwidth_top,
    'blocks_fullwidth_bottom'   => $blocks_fullwidth_bottom,
    'blocks_above_content'      => $blocks_above_content,
    'has_blocks_above_content'  => !empty($blocks_above_content),
    'blocks_below_content'      => $blocks_below_content,
    'has_blocks_below_content'  => !empty($blocks_below_content),
    'has_blocks_fullwidth_top'  => !empty($blocks_fullwidth_top),
    'regionmainsettingsmenu'    => $regionmainsettingsmenu,
    'hasregionmainsettingsmenu' => !empty($regionmainsettingsmenu),
    'edmo_globalsearch_navbar' => $edmo_globalsearch_navbar,
    'logo_visibility'           => $logo_visibility,
    'main_logo'                 => $main_logo,
    'logo_styles'               => $logo_styles,
    'mobile_logo'               => $mobile_logo,
    'mobile_logo_styles'        => $mobile_logo_styles,
    'header_search_bar'         => $header_search,
    'header_btn_text'           => $header_btn_text,
    'header_btn_url'            => $header_btn_url,
    'header_btn_icon'           => $header_btn_icon,
    
    'favicon'                   => $favicon,
    'hide_global_banner'     => $hide_global_banner == 0,

    'footer_logo_visibility'    => $footer_logo_visibility,
    'main_footer_logo'          => $main_footer_logo,
    'footer_logo_styles'        => $footer_logo_styles,
    'social_target_href' => $social_target_href,
    'edmo_facebook_url' => get_config('theme_edmo', 'edmo_facebook_url'),
    'edmo_twitter_url' => get_config('theme_edmo', 'edmo_twitter_url'),
    'edmo_instagram_url' => get_config('theme_edmo', 'edmo_instagram_url'),
    'edmo_pinterest_url' => get_config('theme_edmo', 'edmo_pinterest_url'),
    'edmo_dribbble_url' => get_config('theme_edmo', 'edmo_dribbble_url'),
    'edmo_google_url' => get_config('theme_edmo', 'edmo_google_url'),
    'edmo_youtube_url' => get_config('theme_edmo', 'edmo_youtube_url'),
    'edmo_vk_url' => get_config('theme_edmo', 'edmo_vk_url'),
    'edmo_500px_url' => get_config('theme_edmo', 'edmo_500px_url'),
    'edmo_behance_url' => get_config('theme_edmo', 'edmo_behance_url'),
    'edmo_digg_url' => get_config('theme_edmo', 'edmo_digg_url'),
    'edmo_flickr_url' => get_config('theme_edmo', 'edmo_flickr_url'),
    'edmo_foursquare_url' => get_config('theme_edmo', 'edmo_foursquare_url'),
    'edmo_linkedin_url' => get_config('theme_edmo', 'edmo_linkedin_url'),
    'edmo_medium_url' => get_config('theme_edmo', 'edmo_medium_url'),
    'edmo_meetup_url' => get_config('theme_edmo', 'edmo_meetup_url'),
    'edmo_snapchat_url' => get_config('theme_edmo', 'edmo_snapchat_url'),
    'edmo_tumblr_url' => get_config('theme_edmo', 'edmo_tumblr_url'),
    'edmo_vimeo_url' => get_config('theme_edmo', 'edmo_vimeo_url'),
    'edmo_wechat_url' => get_config('theme_edmo', 'edmo_wechat_url'),
    'edmo_whatsapp_url' => get_config('theme_edmo', 'edmo_whatsapp_url'),
    'edmo_wordpress_url' => get_config('theme_edmo', 'edmo_wordpress_url'),
    'edmo_weibo_url' => get_config('theme_edmo', 'edmo_weibo_url'),
    'edmo_telegram_url' => get_config('theme_edmo', 'edmo_telegram_url'),
    'edmo_moodle_url' => get_config('theme_edmo', 'edmo_moodle_url'),
    'edmo_amazon_url' => get_config('theme_edmo', 'edmo_amazon_url'),
    'edmo_slideshare_url' => get_config('theme_edmo', 'edmo_slideshare_url'),
    'edmo_soundcloud_url' => get_config('theme_edmo', 'edmo_soundcloud_url'),
    'edmo_leanpub_url' => get_config('theme_edmo', 'edmo_leanpub_url'),
    'edmo_xing_url' => get_config('theme_edmo', 'edmo_xing_url'),
    'edmo_bitcoin_url' => get_config('theme_edmo', 'edmo_bitcoin_url'),
    'edmo_twitch_url' => get_config('theme_edmo', 'edmo_twitch_url'),
    'edmo_gitlab_url' => get_config('theme_edmo', 'edmo_gitlab_url'),
    'edmo_forumbee_url' => get_config('theme_edmo', 'edmo_forumbee_url'),
    'edmo_trello_url' => get_config('theme_edmo', 'edmo_trello_url'),
    'edmo_weixin_url' => get_config('theme_edmo', 'edmo_weixin_url'),
    'edmo_slack_url' => get_config('theme_edmo', 'edmo_slack_url'),

    'footer_copyright' => $footer_copyright,
    'banner_shape_image'               => $banner_shape_image,
    'back_to_top' => $back_to_top == 0,
    'dashboard_left_side' => $dashboard_left_side == 0,

    'footer_column_1' => $footer_column_1,
    'footer_column_2' => $footer_column_2,
    'footer_column_3' => $footer_column_3,
    'footer_column_4' => $footer_column_4,
    'footer_column_5' => $footer_column_5,
    'footer_col_1_class' => $footer_col_1_class,
    'footer_col_2_class' => $footer_col_2_class,
    'footer_col_3_class' => $footer_col_3_class,
    'footer_col_4_class' => $footer_col_4_class,
    'footer_col_5_class' => $footer_col_5_class,
    'footer_col_1_title' => get_config('theme_edmo', 'footer_col_1_title'),
    'footer_col_1_body' => format_text(get_config('theme_edmo', 'footer_col_1_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_2_title' => get_config('theme_edmo', 'footer_col_2_title'),
    'footer_col_2_body' => format_text(get_config('theme_edmo', 'footer_col_2_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_3_title' => get_config('theme_edmo', 'footer_col_3_title'),
    'footer_col_3_body' => format_text(get_config('theme_edmo', 'footer_col_3_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_4_title' => get_config('theme_edmo', 'footer_col_4_title'),
    'footer_col_4_body' => format_text(get_config('theme_edmo', 'footer_col_4_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_5_title' => get_config('theme_edmo', 'footer_col_5_title'),
    'footer_col_5_body' => format_text(get_config('theme_edmo', 'footer_col_5_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),

];
$PAGE->requires->jquery();